version: 1.5.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
  - nuget restore
build_script:
- cmd: >-
    msbuild MockHttpServer.sln /p:Configuration=Release
artifacts:
- path: Artifacts
  name: NuGet
